// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuedrwwniualphtpimpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1ZWRyd3duaXVhbHBodHBpbXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMzg3NTgsImV4cCI6MjA2NjcxNDc1OH0.IXmWR5C9XdO5HUBMw2NRipEHTPy1_1T2kbVkk6BkOIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);